version: '3'

services:
    db:
        image: postgres
    django:
        build: .
        command: gunicorn -b 0.0.0.0:5000 --workers=2 danubio.wsgi
        expose:
            - "5000"
        volumes:
            - /static:/static
        environment:
            - DJANGO_ENV=production
        depends_on:
            - db
    nginx:
        image: nginx
        build: ./nginx/
        restart: always
        ports:
            - 80:80
        volumes:
            - /static:/static
        depends_on:
            - django
