# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-07-05 21:21
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('receita', '0003_receita_rendimento'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='receita',
            options={'ordering': ('produto__nome',)},
        ),
    ]
