# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-07-05 01:41
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('receita', '0002_auto_20170704_2351'),
    ]

    operations = [
        migrations.AddField(
            model_name='receita',
            name='rendimento',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
    ]
