# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-07-10 00:25
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('produto', '0002_auto_20170705_2121'),
    ]

    operations = [
        migrations.AddField(
            model_name='produto',
            name='preco',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=8, verbose_name='Preço'),
            preserve_default=False,
        ),
    ]
